// gigastt Android library (AAR).
//
// Packages the gigastt-uniffi native libraries (one libgigastt_uniffi.so per ABI
// under src/main/jniLibs/<abi>/, produced by cargo-ndk) plus the UniFFI-generated
// Kotlin bindings (src/main/kotlin/, produced by uniffi-bindgen) into an AAR.
// onnxruntime is statically linked into each .so, so the AAR is self-contained;
// the ~215 MB model is side-loaded at runtime. The native libs + Kotlin are
// generated by the android-aar workflow before `assembleRelease` (they are not
// committed — see .gitignore).
import org.gradle.api.publish.maven.MavenPublication

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    `maven-publish`
}

android {
    namespace = "com.github.ekhodzitsky.gigastt"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        consumerProguardFiles("consumer-rules.pro")
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {
    // UniFFI's Kotlin bindings call the native library through JNA.
    implementation("net.java.dev.jna:jna:5.14.0@aar")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
}

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = (project.findProperty("GROUP") as String?) ?: "com.github.ekhodzitsky"
            artifactId = (project.findProperty("POM_ARTIFACT_ID") as String?) ?: "gigastt"
            version = (project.findProperty("VERSION_NAME") as String?) ?: "2.3.0"
            afterEvaluate { from(components["release"]) }
            pom {
                name.set("gigastt")
                description.set("On-device Russian speech-to-text (GigaAM v3) — Android bindings")
                url.set("https://github.com/ekhodzitsky/gigastt")
                licenses { license { name.set("MIT") } }
            }
        }
    }
    // Publish target is injected at release time (Sonatype / GitHub Packages)
    // via gradle properties + credentials from CI secrets.
}
